In [1]:
import pandas as pd

def clean_csv(filename):
  """
  Cleans the CSV file by removing unnecessary lines.

  Args:
      filename: The path to the CSV file.

  Returns:
      None
  """
  with open(filename, 'r') as f, open(filename, 'w') as f_out:
    for line in f:
      if line.startswith('"Country Name"'):
        f_out.write(line)

def load_data(filename):
  """
  Loads and transforms the CSV data into a pandas DataFrame.

  Args:
      filename: The path to the CSV file.

  Returns:
      A pandas DataFrame containing the cleaned and transformed data.
  """
  df = pd.read_csv(filename)
  df = df.loc[:, 'Indicator Name':'2022'].drop('Indicator Code', axis=1)
  df = df.set_index(['Country Name', 'Indicator Name']).T
  df.columns = df.iloc[0]
  df = df[1:]
  df.index.name = 'Year'
  return df

# Clean the CSV file
clean_csv("../data/us_data.csv")

# Load and transform the data
df = load_data("../data/us_data.csv")

# Print the DataFrame
print(df)

,Year,"Internally displaced persons, new displacement associated with disasters (number of cases)",Voice and Accountability: Estimate,High-technology exports (current US$),Merchandise exports to low- and middle-income economies within region (% of total merchandise exports),Merchandise exports to low- and middle-income economies in South Asia (% of total merchandise exports),Merchandise exports to low- and middle-income economies in East Asia & Pacific (% of total merchandise exports),Merchandise exports to economies in the Arab World (% of total merchandise exports),ICT goods exports (% of total goods exports),Export unit value index (2015 = 100),...,CPIA economic management cluster average (1=low to 6=high),"Trademark applications, nonresident, by count","Industrial design applications, resident, by count",Public private partnerships investment in ICT (current US$),Investment in ICT with private participation (current US$),Total tax and contribution rate (% of profit),Number of visits or required meetings with tax officials (average for affected firms),"Start-up procedures to register a business, male (number)","Time required to start a business, female (days)","Cost of business start-up procedures, female (% of GNI per capita)"
0,1960,NaN,NaN,NaN,NaN,4.075968,2.853664,2.551741,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1961,NaN,NaN,NaN,NaN,3.397109,3.750179,3.020182,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1962,NaN,NaN,NaN,NaN,4.5198,3.543671,3.474278,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1963,NaN,NaN,NaN,NaN,5.29753,3.570354,2.930183,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1964,NaN,NaN,NaN,NaN,5.123848,2.609122,3.047123,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,2018,1247000.0,0.995732,153808462622.0,NaN,2.398344,10.447887,3.602897,8.896843,102.421308,...,NaN,194236.0,22825.0,NaN,NaN,43.8,NaN,6.0,5.6,1.0
59,2019,916000.0,0.905322,153923490830.0,NaN,2.477851,9.818631,3.817045,8.742109,101.614205,...,NaN,212439.0,22988.0,NaN,NaN,36.6,NaN,6.0,4.2,1.0
60,2020,1715000.0,0.855866,141538563122.0,NaN,2.326888,12.202223,3.189219,9.674849,98.789346,...,NaN,320860.0,21686.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,2021,573000.0,0.878147,169217253983.0,NaN,NaN,NaN,NaN,9.065264,112.510089,...,NaN,347735.0,21913.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,2022,675000.0,0.845122,166435572426.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN